### ISSUE TITLE
Community members plural should allow * for inclusiveness

### ISSUE THREAD

**Issue by uiboy** [OpenbookOrg/openbook-api#213]
In certain languages, plurals include * for inclusiveness .. for eg. in german... member*s is gender neutral and inclusive.. see image: 

<img width="676" alt="Screenshot 2019-03-22 at 12 01 30" src="https://user-images.githubusercontent.com/5570900/54835792-28e5e700-4cc3-11e9-9096-403ac7142a33.png">

**Comment by lifenautjoe** [comment]
Already done with 0.0.19
