### ISSUE TITLE
Testing app in local network

### ISSUE THREAD

**Issue by ehsanmqn** [OpenbookOrg/openbook-api#445]
Hi,
I want to test openbook-app in a local network. Currently, openbook-api is running on a VM and is listening to port 0.0.0.0:8000. I also compiled openbook-app and it's is running on an Android device. How I am able to login? Guide me please

**Comment by Komposten** [comment]
Go to your api folder and run the following:
`pipenv shell`
`python manage.py create_invite`

Copy the invite token that the server replies with.

Now go to the app, click "Create account" and paste `https://[SERVER_IP]:8000/api/auth/invite?token=[YOUR_TOKEN_HERE]` when it asks for an invite link. Replace `[SERVER_IP]` with the IP of the server, either a local IP (starts with 192.168.) or your public IP, and [YOUR_TOKEN_HERE] with the token you got from create_invite above.

In the future, it is better if you ask questions in the #contributors channel in the [Openspace Slack](https://join.slack.com/t/openbookorg/shared_invite/enQtNDI2NjI3MDM0MzA2LTYwM2E1Y2NhYWRmNTMzZjFhYWZlYmM2YTQ0MWEwYjYyMzcxMGI0MTFhNTIwYjU2ZDI1YjllYzlhOWZjZDc4ZWY).

**Comment by lifenautjoe** [comment]
Thank you @Komposten !
