### ISSUE TITLE
A password reset/change does not clear all active sessions

### ISSUE THREAD

**Issue by Arcus92** [OpenbookOrg/openbook-api#447]
When you reset or change your password you are still logged in on all your devices. The old sessions are still active and valid.

This could be a security problem. When your account is compromised/hacked you have no method (known to me) to lock out the attacker of your account.

The simplest solution is to clear all sessions when resetting/changing your password.

**Comment by lifenautjoe** [comment]
Thank you @Arcus92 , we've merged the fix.

Multi-device management is in our next security TODO list.
